You are a teacher and you have different student records containing student id and mark list in each course where different students have opted for different course. Compute average marks for each student and display it.

In [1]:
def getdatafromuser():    # take input as id and marks from user and store it in a dictionary
    D={}
    while True:
        studentid = input("Enter the student id:")
        markslist = input("Enter the marks using commas:")
        morestudents = input('Enter "NO" to quit insertion')
        if studentid in D:
            print(studentid, "is already inserted")
        else:
            D[studentid] =markslist.split(",")
        if morestudents.lower() == "no":
            return D

In [2]:
studentData = getdatafromuser()  #Calling the function

Enter the student id:1
Enter the marks using commas:88,99,50
Enter "NO" to quit insertionhjb
Enter the student id:1
Enter the marks using commas:88,99
Enter "NO" to quit insertionmo
1 is already inserted
Enter the student id:2
Enter the marks using commas:66,99,88
Enter "NO" to quit insertionno


In [3]:
def getavgmarks(D):    # find the sum of the marks and perform average
    avgmarks = {}
    for x in D:
        L = D[x]
        s=0   
        for marks in L:
            s+= int(marks)
        avgmarks[x] = s/len(L)
    return avgmarks

In [4]:
avgm = getavgmarks(studentData)

In [5]:
for x in avgm:
    print("Student:",x,"has got average marks:", avgm[x])

Student: 1 has got average marks: 79.0
Student: 2 has got average marks: 84.33333333333333


# Data science packages - Numpy

In [6]:
import numpy as np

In [9]:
a = np.array([1,2,3,4,5])

In [10]:
print(a)


[1 2 3 4 5]


In [11]:
b = np.array([6,7,8,9,10])
print(b)

[ 6  7  8  9 10]


# Properties of numpy

In [12]:
a.dtype  # display datatype

dtype('int32')

In [13]:
a.ndim  # n dimensional

1

In [2]:
c = np.array([[[1,2],[3,4]]   ,  [[5,6],[7,8]]  ,  [[9,10],[11,12]]])

In [3]:
c.ndim #display number of dimensions eg: 1d, 2d, 3d...

3

In [16]:
c

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [20]:
c.shape  #how many arrays and elements in the array

(3, 2, 2)

In [21]:
c.size # total number of elements in your numpy array

12

In [19]:
A = np.arange(5)
print(A)

[0 1 2 3 4]


In [62]:
A = np.arange(96,100)
print(A)

[96 97 98 99]


In [7]:
A = np.arange(17,27,4)
print(A)

[17 21 25]


In [24]:
A = np.random.permutation(np.arange(5))
print(A)

[0 4 2 1 3]


In [21]:
np.random.randint(45,89)

66

In [16]:
np.matmul?

In [36]:
np.fill_diagonal?

In [37]:
help(np.add_docstring)

Help on built-in function add_docstring in module numpy.core._multiarray_umath:

add_docstring(...)
    add_docstring(obj, docstring)
    
    Add a docstring to a built-in obj if possible.
    If the obj already has a docstring raise a RuntimeError
    If this routine does not know how to add a docstring to the object
    raise a TypeError



In [17]:
a = np.array([[1, 0],              [0, 1]])
b = np.array([[4, 1],              [2, 2]])
np.matmul(a, b)

array([[4, 1],
       [2, 2]])