In [1]:
import numpy as np

In [2]:
import numpy.linalg as la

In [3]:
la.inv(np.random.rand(3,3))    #Calculate inverse of a matrix using linear algebra package

array([[ 0.64865624,  0.80371399, -1.12094551],
       [ 3.45639966, -2.02091049, -2.01518696],
       [-3.42329068,  1.76828748,  3.60476854]])

In [4]:
A = np.arange(61)

In [5]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [6]:
B = A[A<40]  #Access elements that are less than 40

In [7]:
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [10]:
B = A[(A<40) & (A>30)]   #Access elements that are in between 30 and 40

In [11]:
B

array([31, 32, 33, 34, 35, 36, 37, 38, 39])

In [12]:
A = np.round(10*np.random.rand(2,3))

In [13]:
A

array([[ 4.,  9.,  3.],
       [ 9., 10.,  6.]])

In [14]:
A+3

array([[ 7., 12.,  6.],
       [12., 13.,  9.]])

In [15]:
B = np.round(10*np.random.rand(2,2))

In [16]:
B    # Matrix of size 2x2

array([[5., 9.],
       [3., 2.]])

In [17]:
A   #Matrix of size 2x3

array([[ 4.,  9.,  3.],
       [ 9., 10.,  6.]])

In [18]:
C = np.hstack((A,B))  #Concatenation of 2 matrices

In [19]:
C

array([[ 4.,  9.,  3.,  5.,  9.],
       [ 9., 10.,  6.,  3.,  2.]])

# Speed of universal function  - Program to calculate sum of a large number


1. Python function  = 70 ms
2. Numpy  = 1.21 ms
3. Creating our own function = 99 ms

In [20]:
B = np.random.rand(1000000)   

In [21]:
%timeit sum(B) #Method 1 : Use in-built python function

70 ms ± 330 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [22]:
%timeit np.sum(B) #Method 2: Use Numpy

1.21 ms ± 128 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [23]:
def my_own_func(G):      #Method 3: Create your own function
    s=0
    for x in G:
        s+=x
    return s

In [24]:
%timeit my_own_func(B)

99.7 ms ± 3.94 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


# Pandas

In [25]:
import pandas as pd

In [26]:
A = pd.Series([2,3,4,5], index=['a','b','c','d'])

In [27]:
A.values

array([2, 3, 4, 5], dtype=int64)

In [28]:
A.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [29]:
A['a']

2

In [30]:
A['a':'c']

a    2
b    3
c    4
dtype: int64

In [31]:
grades_dict = {'A':4,'B':3.5, 'C':3, 'D':2.5}

In [32]:
grades = pd.Series(grades_dict)

In [33]:
marks_dict = {'A':85,'B':75,'C':65,'D':55}

In [34]:
marks = pd.Series(marks_dict)

In [35]:
grades

A    4.0
B    3.5
C    3.0
D    2.5
dtype: float64

In [36]:
marks

A    85
B    75
C    65
D    55
dtype: int64

In [37]:
D = pd.DataFrame({'Marks':marks,'Grades':grades})

In [38]:
D

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [39]:
D.T

A     B     C     D
Marks   85.0  75.0  65.0  55.0
Grades   4.0   3.5   3.0   2.5

In [40]:
D

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [42]:
D['Percentage'] = (D['Marks']/100)  #adding a new column

In [43]:
D

Marks  Grades  Percentage
A     85     4.0        0.85
B     75     3.5        0.75
C     65     3.0        0.65
D     55     2.5        0.55

In [44]:
del D['Percentage']   #deleting any column

In [45]:
D

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

    # Handling missing values (NaN)

In [46]:
A = pd.DataFrame([{'a':1,'b':-7},{'b':9,'c':65}])

In [47]:
A

a  b     c
0  1.0 -7   NaN
1  NaN  9  65.0

In [48]:
A.fillna(0)  #fill the NaN / missing values

a  b     c
0  1.0 -7   0.0
1  0.0  9  65.0

In [50]:
A.dropna()

Empty DataFrame
Columns: [a, b, c]
Index: []